packages:
  - "apps/*"
  - "libs/*"
  - "libs/ledgerjs/**"
  - "libs/ui/packages/*"
  - "libs/ledger-live-common/cli"
  - "libs/ledger-live-common/tools"
  - "libs/ledger-live-common/bot-react-native"
  - "tools/**"
